global using Xunit;
global using FluentAssertions;
global using System.Net;
global using Newtonsoft.Json;
global using RabbitMq.DAL;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
