name: Docker Build Image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  
env:
  USERNAME: ${{ secrets.USERNAME }}
  GH_AUTH_TOKEN: ${{ secrets.GhAuthToken }}
  IMAGE_NAME: rabbitmq
  IMAGE_TAG: ${{ secrets.IMAGETAG }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image WebAPI
      working-directory: RabbitMq.WebAPI
      run: docker build . --file Dockerfile --tag ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }}
      
    - name: Login to ghcr.io
      run: docker login ghcr.io -u ${{ env.USERNAME }} -p ${{ env.GH_AUTH_TOKEN }}
      
    - name: Push image to ghcr.io
      run: docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }}
