name: Docker Build Image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  
env:
  USERNAME: ${{ secrets.USERNAME }}
  GH_AUTH_TOKEN: ${{ secrets.GhAuthToken }}
  IMAGE_TAG: ${{ secrets.ImageTag }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: print variables
      run: echo $USERNAME $IMAGE_TAG
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: RabbitMq.WebApi
      run: docker build . --file Dockerfile --tag $USERNAME/rabbitmq:v$IMAGE_TAG
